# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:

#    - os: osx
#      language: generic
#      env:
#        - PYTHON_VERSION=3.5.2

#    - os: osx
#      language: generic
#      env:
#        - PYTHON_VERSION=3.4.5

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.12

cache:
  directories:
    - $HOME/.pyenv/versions/3.5.2
    - $HOME/.pyenv/versions/3.4.5
    - $HOME/.pyenv/versions/2.7.12
    - $HOME/downloads

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; fi
  - pip install scikit-ci==0.13.0 scikit-ci-addons==0.11.0
  - ci_addons --install ../addons

install:
  - ci install

script:
  - ci test

after_success:
  - ci after_test

before_deploy:
  - sudo pip install twine  # Twine installation requires sudo to get access to /usr/local/man
deploy:
  provider: script
  skip_cleanup: true
  script: twine upload --repository-url https://test.pypi.org/legacy/ dist/*.whl -u $PYPI_USER -p $PYPI_PASSWORD
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v?[0-9]+(\.[0-9]+)*(-rc[0-9]+)?$
