branches:
 only:
  - master

version: "0.0.1.{build}"

environment:
  matrix:

    # Visual Studio (Python 2 & 3, 64 bit)

    - PYTHON_DIR: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"

    - PYTHON_DIR: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"

    - PYTHON_DIR: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"

init:
  - python -m pip install scikit-ci==0.13.0 scikit-ci-addons==0.11.0
  - python -m ci_addons --install ../addons

  - ps: ../addons/appveyor/rolling-build.ps1

install:
  - python -m ci install

build_script:
  - python -m ci build

test_script:
  - python -m ci test

after_test:
  - python -m ci after_test

on_finish:
  - ps: ../addons/appveyor/enable-worker-remote-access.ps1 -check_for_block

deploy:
  - name: release
    on:
      APPVEYOR_REPO_TAG: true
    ps: |
          if ($env:APPVEYOR_REPO_TAG_NAME -notmatch '^V?\d(\.\d)*(-rc\d+)?$') { appveyor exit }
          python -m pip install twine
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*.whl -u $env:PYPI_USER -p $env:PYPI_PASSWORD

matrix:
  fast_finish: false
