# To test:
# docker pull circleci/picard
# docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):$(pwd) -v ~/.circleci/:/root/.circleci --workdir $(pwd) circleci/picard circleci build

version: 2.1
jobs:
  test-notebooks:
    working_directory: /pyradiomics
    docker:
      - image: jupyter/datascience-notebook
        user: root
    steps:
      - run:
          # CircleCI says we need SSH and the docker doesn't have it installed
          name: Update
          command: |
            apt-get update
            apt-get install -y openssh-client openssh-server
      - run:
          name: Avoid hosts unknown for github
          command: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > /etc/ssh/ssh_config
      - checkout
      - run:
          name: Install pyradiomics in Python 3
          command: |
            source activate root
            python -m pip install --no-cache-dir -r requirements.txt
            python -m pip install --no-cache-dir -r requirements-dev.txt
            python setup.py install
      - run:
          name: test notebooks in python 3
          command: |
            jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=-1 --to notebook --output-dir /tmp --execute  notebooks/helloRadiomics.ipynb notebooks/helloFeatureClass.ipynb notebooks/PyRadiomicsExample.ipynb

  build-mac:
    working_directory: ~/pyradiomics
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/pyradiomics
      - run:
          name: Setup MAC OS environment
          # Workaround the following error occurring because python installation is cached but gettext dependency is not
          #   dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
          #     Referenced from: /Users/travis/.pyenv/versions/3.7.2/bin/python
          #     Reason: Incompatible library version: python requires version 11.0.0 or later, but libintl.8.dylib provides version 10.0.0
          # See https://github.com/scikit-build/cmake-python-distributions/issues/112 and
          # https://github.com/scikit-build/cmake-python-distributions/pull/113
          command: |
            brew update
            brew install gettext
            brew install pyenv
            mkdir $HOME/bin
            ln -s $(which pip3) $HOME/bin/pip
            ln -s $(which python3) $HOME/bin/python
      - run:
          name: Setup SciKit-CI
          command: |
            pip install scikit-ci scikit-ci-addons
            ci_addons --install ../addons

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-mac: &build_job_template
          filters:
            tags:
              only:
                - /^v?[0-9]+(\.[0-9]+)*(rc[0-9]+)?/
